version: '3'

services:
  map:
    image: overv/openstreetmap-tile-server
    volumes:
      - ./data:/data/database/
      - ./openptmap:/data/style
      - ./berlin-latest.osm.pbf:/data/region.osm.pbf
      - ./berlin.poly:/data/region.poly
    environment:
      UPDATES: enabled
      # DOWNLOAD_PBF: https://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf
      # DOWNLOAD_POLY: https://download.geofabrik.de/europe/germany/berlin.poly
      NAME_STYLE: output.lua
      OSM2PGSQL_EXTRA_ARGS: -O flex
    ports:
      - "8080:80"
    command: "run"
